import React, { createContext, useContext, useState, useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';

export type Language = 'UZ' | 'RU' | 'EN';

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  UZ: {
    // Nav
    'nav.dashboard': 'Dashboard',
    'nav.superadmin': 'SuperAdmin Boshqaruvi',
    'nav.crm': 'CRM & Lidlar',
    'nav.calendar': 'Dars Jadvali',
    'nav.rooms': 'Xonalar',
    'nav.students': 'O‘quvchilar',
    'nav.teachers': 'O‘qituvchilar',
    'nav.groups': 'Guruhlar',
    'nav.subjects': 'Fanlar',
    'nav.lessons': 'Darslar',
    'nav.attendance': 'Davomat',
    'nav.grades': 'Baholar',
    'nav.homework': 'Uy Vazifalari',
    'nav.payments': 'To‘lovlar',
    'nav.invoices': 'Invoyslar',
    'nav.payroll': 'Oylik & Payroll',
    'nav.risk': 'Risk Tahlili',
    'nav.certificates': 'Sertifikatlar',
    'nav.branches': 'Filiallar',
    'nav.reports': 'Hisobotlar',
    'nav.settings': 'Sozlamalar',
    'nav.my_children': 'Farzandlarim',
    'nav.my_profile': 'Mening Profilim',
    'nav.feedback': 'Fikr bildirish',
    'nav.my_lessons': 'Darslarim',
    'nav.my_groups': 'Guruhlarim',
    'nav.my_salary': 'Oylik Maosh',

    // Roles
    'role.superadmin': 'SuperAdmin',
    'role.admin': 'Administrator',
    'role.teacher': 'O‘qituvchi',
    'role.parent': 'Ota-ona',
    'role.student': 'O‘quvchi',
    'role.user': 'Foydalanuvchi',

    // Header & Common
    'header.search': 'Qidirish (Ctrl + K)...',
    'header.quick_add': 'Qo‘shish',
    'header.new_student': 'Yangi O‘quvchi',
    'header.new_teacher': 'Yangi O‘qituvchi',
    'header.new_group': 'Yangi Guruh',
    'header.take_attendance': 'Davomat Qilish',
    'header.new_lead': 'Yangi Lid (CRM)',
    'header.logout': 'Chiqish',

    // Actions
    'action.add': 'Qo‘shish',
    'action.edit': 'Tahrirlash',
    'action.delete': 'O‘chirish',
    'action.save': 'Saqlash',
    'action.cancel': 'Bekor qilish',
    'action.filter': 'Filtrlash',
    'action.view_all': 'Barchasini ko‘rish',
    'action.loading': 'Yuklanmoqda...',
    'action.attend': 'Davomat',
    'action.grade': 'Baholash',
    'action.submit': 'Yuborish',
    'action.details': 'Batafsil',
    'action.create_homework': '+ Yangi uy vazifasi',

    // Periods
    'period.analysis': 'Tahlil davri:',
    'period.today': 'Bugun',
    'period.7d': '7 kun',
    'period.30d': '30 kun',
    'period.3m': '3 oy',
    'period.6m': '6 oy',
    'period.1y': '1 yil',
    'period.all': 'Barchasi',
    'period.7d_full': 'So‘nggi 7 kun',
    'period.30d_full': 'So‘nggi 30 kun',
    'period.3m_full': 'So‘nggi 3 oy',
    'period.6m_full': 'So‘nggi 6 oy',
    'period.1y_full': 'So‘nggi 1 yil',
    'period.all_full': 'Barcha davr',

    // Theme labels
    'theme.morning': 'Tong',
    'theme.night': 'Tun',
    'theme.auto': 'Avto',

    // Hero Banner & Quick Actions
    'hero.morning_mode': 'Tonggi tetiklik rejimi',
    'hero.night_mode': 'Kechki qulay ko‘z himoyasi',
    'hero.status_active': 'EduFlow Faol',
    'hero.greeting_morning': 'Xayrli kun',
    'hero.greeting_evening': 'Xayrli oqshom',
    'hero.user_fallback': 'Foydalanuvchi',
    'hero.desc_morning': 'Bugun yangi yutuqlar va darslar kuni. O‘quvchilaringiz bilim olishga tayyor!',
    'hero.desc_evening': 'Bugungi darslar, davomat va to‘lovlar hisobotlarini ko‘rib chiqishingiz mumkin. Ko‘zlaringizga dam bering!',
    'hero.quick_attendance': 'Tezkor Davomat Qilish',
    'hero.students': 'O‘quvchilar',
    'hero.payments': 'To‘lovlar',
    'hero.hub_title': 'EduFlow Pro Hub',
    'hero.hub_subtitle': 'Multi-Tenant Smart CRM',
    'hero.quick': 'Tezkor',
    'hero.attendance': 'Davomat',
    'hero.telegram': 'Telegram',
    'hero.notifications': 'Xabarnoma',
    'hero.finance': 'Moliya',
    'hero.safe': 'Xavfsiz',
    'hero.cloud': 'Bulutli Tizim',
    'hero.server_online': 'Server 100% Onlayn',

    'action.register_student_sub': 'Ro‘yxatga olish',
    'action.assign_teacher_sub': 'Mentor biriktirish',
    'action.create_group_sub': 'Kurs ochish',
    'action.quick_mark_sub': 'Tezkor belgilash',

    // Admin Dashboard
    'dash.expected_revenue': 'Kutilayotgan tushum',
    'dash.expected_sub': 'Davr bo‘yicha kurs to‘lovlari',
    'dash.collected_revenue': 'Yig‘ilgan tushum',
    'dash.collected_sub': 'Haqiqiy to‘langan',
    'dash.debt': 'Qarzdorlik',
    'dash.debt_sub': 'Undirilishi lozim',
    'dash.net_revenue': 'Markaz sof tushumi',
    'dash.net_sub': 'Oyliklar chegirilgach',
    'dash.attendance_rate': 'Davomat ko‘rsatkichi',
    'dash.attendance_sub': 'O‘rtacha dars qatnashuvi',
    'dash.average_grade': 'O‘rtacha baho',
    'dash.average_grade_sub': 'Akademik o‘zlashtirish',
    'dash.room_occupancy': 'Xonalar bandligi',
    'dash.active_rooms_suffix': 'ta faol xona',
    'dash.risk_group': 'Risk guruhi',
    'dash.students_unit': 'nafar',
    'dash.total_students': 'O‘quvchilar',
    'dash.active_students': 'Faol o‘quvchilar',
    'dash.teachers_count': 'O‘qituvchilar',
    'dash.mentors_teachers': 'Mentor & Ustozlar',
    'dash.active_groups': 'Faol Guruhlar',
    'dash.study_groups': 'O‘quv guruhlari',
    'dash.today_lessons': 'Bugungi Darslar',
    'dash.scheduled_lessons': 'Jadvaldagi darslar',
    'dash.today_lessons_schedule': 'Bugungi Darslar Jadvali',
    'dash.no_lessons_today': 'Bugun uchun darslar belgilanmagan',
    'dash.teacher_prefix': 'O‘qituvchi:',
    'dash.unassigned': 'Biriktirilmagan',
    'dash.students_prefix': 'O‘quvchilar:',
    'dash.no_topic': 'Mavzu kiritilmagan',
    'dash.time': 'Vaqt',
    'dash.due_date_prefix': 'Muddat:',
    'dash.overdue_payments': 'Qarzdorliklar',
    'dash.no_overdue': 'Muddati o‘tgan qarzdorliklar mavjud emas',
    'dash.monthly_revenue': 'Oylik tushum',
    'dash.high_risk_desc': 'Chiqib ketish xavfi bor',
    'dash.attendance_desc': 'O‘quv markazidagi o‘quvchilarning umumiy darslarga qatnashish intizomi ko‘rsatkichi.',
    'dash.view_detailed_report': 'Batafsil hisobotni ko‘rish →',

    // Teacher Dashboard
    'teacher.welcome': 'Xush kelibsiz',
    'teacher.badge': 'O‘qituvchi Paneli',
    'teacher.my_groups_count': 'Guruhlarim',
    'teacher.my_students_count': 'O‘quvchilarim',
    'teacher.today_lessons_count': 'Bugungi darslarim',
    'teacher.monthly_earnings': 'Oylik Maosh (Hisoblangan)',
    'teacher.attendance_rate': 'O‘rtacha Davomat',
    'teacher.today_schedule': 'Bugungi Darslarim Jadvali',
    'teacher.weekly_timetable': 'Haftalik Dars Jadvali',
    'teacher.my_groups_list': 'Biriktirilgan Guruhlarim',
    'teacher.homework_title': 'Uyga Vazifalar Holati',
    'teacher.recent_grades': 'So‘nggi Baholangan O‘quvchilar',
    'teacher.quick_actions': 'Tezkor Amallar',
    'teacher.take_attendance_btn': 'Davomat belgilash',
    'teacher.new_homework_btn': 'Uy vazifasi berish',
    'teacher.give_grade_btn': 'Baho qo‘yish',
    'teacher.view_calendar_btn': 'Taqvimni ko‘rish',
    'teacher.room': 'Xona',
    'teacher.time': 'Vaqt',
    'teacher.group': 'Guruh',
    'teacher.subject': 'Fan',
    'teacher.topic': 'Mavzu',
    'teacher.students_count': 'o‘quvchi',
    'teacher.attendance_taken': 'Davomat olindi',
    'teacher.attendance_pending': 'Davomat olinmagan',
    'teacher.no_today_lessons': 'Bugun uchun sizda rejalashtirilgan darslar yo‘q',
    'teacher.no_homeworks': 'Hozircha faol uy vazifalari mavjud emas',
    'teacher.due_date': 'Topshirish muddati',
    'teacher.submissions': 'Topshirganlar',
    'teacher.base_salary': 'Asosiy maosh',
    'teacher.share_percent': 'Dars ulushi foizi',
    'teacher.payroll_status': 'Maosh holati',
    'teacher.payroll_paid': 'To‘langan',
    'teacher.payroll_pending': 'Kutilmoqda',
    'teacher.hero_desc': 'Bugungi darslaringiz jadvali, o‘quvchilar davomati, baholari va oylik daromadingiz hisob-kitobini quyida kuzatishingiz mumkin.',
    'teacher.active_groups_sub': 'Faol dars guruhlari',
    'teacher.enrolled_students_sub': 'Guruhlarga biriktirilgan',
    'teacher.monthly_share_sub': 'Ushbu oydagi ulush',
    'teacher.payroll_analysis_title': 'Oylik Maosh & Ulush Tahlili',
    'teacher.calculated_for_month': 'Ushbu oy uchun hisoblangan:',
    'teacher.payroll_auto_note': 'O‘quvchilar tomonidan to‘langan kurs to‘lovlari asosida avtomatik hisoblab boriladi.',
    'teacher.interactive_calendar_title': 'Interaktiv Dars Jadvali',
    'teacher.interactive_calendar_desc': 'Haftalik barcha darslar va xonalar taqvimi',
    'teacher.open_calendar_btn': 'Dars jadvalini ochish →',
    'teacher.score_unit': 'ball',

    // Parent Dashboard
    'parent.welcome': 'Xush kelibsiz, ota-ona',
    'parent.children': 'Farzandlarim',
    'parent.child_attendance': 'Davomat ko‘rsatkichi',
    'parent.child_grades': 'Oxirgi baholar',
    'parent.child_homework': 'Uy vazifalari',
    'parent.child_invoices': 'To‘lov va Hisob-kitoblar',
    'parent.schedule': 'Dars jadvali',
    'parent.contact_center': 'Markaz bilan bog‘lanish',

    // Statuses
    'status.active': 'Faol',
    'status.inactive': 'Nofaol',
    'status.scheduled': 'Rejalashtirilgan',
    'status.completed': 'Tugallangan',
    'status.cancelled': 'Bekor qilingan',
    'status.present': 'Keldi',
    'status.absent': 'Kelmadi',
    'status.late': 'Kechikdi',
    'status.excused': 'Sababli',
    'status.paid': 'To‘langan',
    'status.pending': 'Kutilmoqda',
    'status.overdue': 'Qarzdorlik',

    // Children / Portal
    'children.demo_notice_title': 'Namunaviy farzandlar profili ko‘rinishi',
    'children.demo_notice_desc': 'Tizim yangi boshlanganligi sababli quyida namunaviy farzandlar profillari ko‘rsatilmoqda. Farzandingiz ma\'lumotlarini markaz administratoridan biriktirishingiz mumkin.',
    'children.connect_child': '+ Farzandni ulash',
    'children.mgmt_badge': 'Farzandlarim boshqaruvi',
    'children.title': 'Mening Farzandlarim',
    'children.subtitle': 'Har bir farzandingizning dars jadvali, o‘qituvchilari, davomat daftari, baholari va oylik to‘lovlarini alohida boshqaring.',
    'children.link_new_btn': 'Yangi farzand biriktirish',
    'children.active_student': 'Faol o‘quvchi',
    'children.debt': 'Qarzdorlik',
    'children.paid': 'To‘langan',
    'children.attendance': 'Davomat',
    'children.attendance_sub': 'Qatnashuv',
    'children.avg_grade': 'O‘rtacha baho',
    'children.avg_grade_sub': 'Akademik',
    'children.groups': 'Guruhlar',
    'children.groups_sub': 'Biriktirilgan',
    'children.assigned_courses': 'Biriktirilgan kurslar va guruhlar:',
    'children.teacher': 'Ustoz:',
    'children.monthly_tuition': 'Oylik to‘lov:',
    'children.view_full_profile': 'To‘liq ma\'lumotlarni ko‘rish',
    'children.no_children_title': 'Farzandlar topilmadi',
    'children.no_children_desc': 'Sizning hisobingizga hali birorta ham o‘quvchi biriktirilmagan. Markaz administratori orqali yoki pastdagi tugmani bosib yangi farzand biriktiring.',
    'children.tab_schedule': 'Dars Jadvali',
    'children.tab_attendance': 'Davomat daftari',
    'children.tab_grades': 'Baholar',
    'children.tab_payments': 'To‘lov & Invoyslar',
    'children.present': 'Bor',
    'children.absent': 'Yo‘q',
    'children.late': 'Kechikdi',
    'children.pay_with_payme': 'Payme orqali to‘lash',
    'children.pay_with_click': 'Click orqali to‘lash',
    'children.pay_with_uzum': 'Uzum orqali to‘lash',
    'children.close': 'Yopish',
    'children.link_modal_title': 'Yangi farzandni markazga biriktirish',
    'children.link_modal_desc': 'Farzandingizning telefon raqami yoki o‘quvchi ID sini kiriting. Markaz administratorlari tasdiqlagach, u sizning profilingizda to‘liq ko‘rinadi.',
    'children.search_placeholder': '+998 90 123 45 67 yoki O‘quvchi ID...',
    'children.send_request': 'Biriktirish so‘rovini yuborish',
    'children.request_sent': 'So‘rov muvaffaqiyatli yuborildi! Markaz administratori tasdiqlashini kuting.',

    // Feedback
    'feedback.page_title': 'Fikr-mulohazalar va Takliflar',
    'feedback.page_subtitle': 'Markaz faoliyati, o‘qituvchilar va darslar haqida o‘z fikringizni bildiring',
    'feedback.new_feedback': 'Yangi fikr bildirish',
    'feedback.target_label': 'Kim/Nima haqida fikr bildirasiz?',
    'feedback.target_center': 'O‘quv markazi haqida',
    'feedback.target_teacher': 'O‘qituvchi haqida',
    'feedback.target_course': 'Kurs va darslar',
    'feedback.target_general': 'Boshqa taklif',
    'feedback.select_teacher': 'O‘qituvchini tanlang',
    'feedback.rating_label': 'Baho (Yulduzlar)',
    'feedback.comment_placeholder': 'Taassurotlaringiz, taklif yoki e\'tirozlaringizni batafsil yozing...',
    'feedback.submit_btn': 'Fikrni yuborish',
    'feedback.success_msg': 'Fikringiz muvaffaqiyatli yuborildi! Rahmat.',
    'feedback.history_title': 'Barcha fikr-mulohazalar',
    'feedback.no_feedback': 'Hozircha hech qanday fikr bildirilmagan',

    // Student Portal
    'student.badge': 'O‘quvchi profili',
    'student.greeting': 'Salom',
    'student.hero_desc': 'Darslaringiz jadvali, uy vazifalarini topshirish va natijalaringizni kuzatib boring.',
    'student.my_groups': 'Guruhlarim',
    'student.active_courses': 'Faol kurslar',
    'student.groups_unit': 'ta guruh',
    'student.attendance': 'Davomat',
    'student.attendance_sub': 'Darslarga qatnashish',
    'student.avg_grade': 'O‘rtacha baho',
    'student.academic_perf': 'Akademik o‘zlashtirish',
    'student.homework_title': 'Uy vazifalari',
    'student.pending_count_suffix': 'ta kutilmoqda',
    'student.due_date_active': 'Topshirish muddati bor',
    'student.my_homework_section': 'Mening Uy Vazifalarim',
    'student.tasks_unit': 'ta vazifa',
    'student.graded_badge': 'Baholandi',
    'student.submitted_badge': 'Topshirilgan',
    'student.due_date': 'Muddat',
    'student.teacher_comment': 'O‘qituvchi sharhi',
    'student.resubmit_btn': 'Qayta topshirish / Tahrirlash',
    'student.submit_btn': 'Vazifani topshirish',
    'student.no_homework': 'Hozircha hech qanday uy vazifasi berilmagan.',
    'student.upcoming_lessons': 'Yaqinlashayotgan darslar',
    'student.no_upcoming': 'Yaqin orada darslar yo‘q.',
    'student.my_certificates': 'Sertifikatlarim',
    'student.issued_date': 'Berilgan sana',
    'student.verify_btn': 'Tekshirish',
    'student.no_certificates': 'Hozircha sertifikatlar berilmagan.',
    'student.submit_modal_title': 'Vazifani topshirish',
    'student.submit_success_title': 'Muvaffaqiyatli!',
    'student.submit_success_desc': 'Vazifangiz o‘qituvchiga tekshirish uchun yuborildi.',
    'student.solution_label': 'Vazifa javobi yoki sharhingiz',
    'student.solution_placeholder': 'Yechim yoki insho matnini bu yerga yozing...',
    'student.attach_file_label': 'Fayl biriktirish (ixtiyoriy: PDF, Word, Rasm)',
    'student.choose_file': 'Fayl tanlash',
    'student.file_attached': 'Fayl biriktirildi',
    'student.loading_portal': 'O‘quvchi kabineti yuklanmoqda...',
    'student.not_found_title': 'Ma‘lumot topilmadi',
    'student.not_found_desc': 'O‘quvchi ma‘lumotlari tizimda topilmadi. Iltimos qaytadan kiring.',

    // Calendar
    'calendar.title': 'Dars Jadvali & Kalendar',
    'calendar.subtitle': 'O‘qituvchilar, guruhlar va xonalar bandligi',
    'calendar.check_conflict': 'Konfliktni tekshirish',
    'calendar.month': 'Oy',
    'calendar.week': 'Hafta',
    'calendar.day': 'Kun',
    'calendar.today': 'Bugun',
    'calendar.all_teachers': 'Barcha o‘qituvchilar',
    'calendar.all_groups': 'Barcha guruhlar',
    'calendar.all_rooms': 'Barcha xonalar',
    'calendar.modal_title': 'Dars Jadvali Konfliktini Tekshirish',
    'calendar.modal_desc': 'Dars qo‘yishdan oldin xona yoki o‘qituvchining boshqa darsi bilan to‘qnashuvini aniqlang.',
    'calendar.start_time': 'Boshlanish vaqti',
    'calendar.end_time': 'Tugash vaqti',
    'calendar.teacher_optional': 'O‘qituvchi (ixtiyoriy)',
    'calendar.room_optional': 'Xona (ixtiyoriy)',
    'calendar.group_optional': 'Guruh (ixtiyoriy)',
    'calendar.select_teacher': 'O‘qituvchini tanlang',
    'calendar.select_room': 'Xonani tanlang',
    'calendar.select_group': 'Guruhni tanlang',
    'calendar.checking': 'Tekshirilmoqda...',
    'calendar.check_btn': 'Tekshirish',
    'calendar.no_conflict': 'Konflikt aniqlanmadi! Belgilangan vaqt bo‘sh.',
    'calendar.conflict_found': 'Konflikt mavjud!',
    'calendar.no_events': 'Ushbu davrda darslar mavjud emas',

    // Common Table & Pagination
    'table.name': 'Ism familiya',
    'table.student': 'O‘quvchi',
    'table.teacher': 'O‘qituvchi',
    'table.group': 'Guruh',
    'table.course': 'Kurs',
    'table.subject': 'Fan',
    'table.phone': 'Telefon',
    'table.parent': 'Ota-onasi',
    'table.status': 'Holati',
    'table.actions': 'Amallar',
    'table.date': 'Sana',
    'table.time': 'Vaqt',
    'table.room': 'Xona',
    'table.amount': 'Summa',
    'table.debt': 'Qarzdorlik',
    'table.attendance': 'Davomat',
    'table.grade': 'Baho',
    'table.telegram': 'Telegram',
    'table.page': 'Sahifa',
    'table.prev': 'Oldingi',
    'table.next': 'Keyingi',

    // Students Management
    'students.title': 'O‘quvchilar Boshqaruvi',
    'students.desc': 'O‘quv markazingizdagi barcha o‘quvchilar, guruhlar taqsimoti, ota-onalar bilan aloqa va oylik davomat monitoringi.',
    'students.total_enrolled': 'Jami ro‘yxatda',
    'students.active_groups': 'Faol guruhlar',
    'students.tg_integration': 'Telegram integratsiya',
    'students.add_new': 'Yangi o‘quvchi qo‘shish',
    'students.search_placeholder': 'Ism, familiya yoki telefon...',
    'students.all_groups': 'Barcha guruhlar',
    'students.loading': 'O‘quvchilar ro‘yxati yuklanmoqda...',
    'students.empty_title': 'Birinchi o‘quvchingizni qo‘shing yoki Demo ma’lumotlarni sinab ko‘ring!',
    'students.empty_sub': 'Yangi o‘quvchi ro‘yxatdan o‘tgach, uning davomati, to‘lovlari va ota-onasi bilan muloqoti avtomatik boshqariladi.',
    'students.modal_add_title': 'Yangi o‘quvchi qo‘shish',
    'students.modal_edit_title': 'O‘quvchi ma’lumotlarini tahrirlash',
    'students.modal_delete_title': 'O‘quvchini o‘chirish',
    'students.delete_confirm': 'Haqiqatan ham ushbu o‘quvchini tizimdan o‘chirmoqchimisiz?',
    'students.first_name': 'Ism',
    'students.last_name': 'Familiya',
    'students.parent_name': 'Ota-onasining F.I.Sh.',
    'students.parent_phone': 'Ota-onasining telefoni',

    // Teachers Management
    'teachers.title': 'O‘qituvchilar va Mentorlar',
    'teachers.desc': 'O‘quv markazi pedagoglar tarkibi, dars soatlari, oylik hisob-kitoblari va guruhlar taqsimoti.',
    'teachers.add_new': 'Yangi o‘qituvchi qo‘shish',
    'teachers.search_placeholder': 'O‘qituvchi ismi yoki telefoni...',
    'teachers.specialization': 'Mutaxassisligi',
    'teachers.salary_type': 'Maosh turi',
    'teachers.base_salary': 'Asosiy stavka',
    'teachers.share_percent': 'Ulush foizi (%)',
    'teachers.fixed': 'Belgilangan oylik',
    'teachers.percentage': 'Foizli ulush',
    'teachers.modal_add_title': 'Yangi o‘qituvchi qo‘shish',
    'teachers.modal_edit_title': 'O‘qituvchi ma’lumotlarini tahrirlash',
    'teachers.modal_delete_title': 'O‘qituvchini o‘chirish',
    'teachers.delete_confirm': 'Haqiqatan ham ushbu o‘qituvchini o‘chirmoqchimisiz?',

    // Groups Management
    'groups.title': 'Guruhlar va Kurslar',
    'groups.desc': 'Barcha o‘quv guruhlari, haftalik dars jadvallari, xonalar taqsimoti va o‘quvchilar soni.',
    'groups.add_new': 'Yangi guruh ochish',
    'groups.search_placeholder': 'Guruh nomi bo‘yicha qidirish...',
    'groups.all_subjects': 'Barcha fanlar',
    'groups.all_teachers': 'Barcha o‘qituvchilar',
    'groups.name': 'Guruh nomi',
    'groups.monthly_fee': 'Oylik to‘lov (so‘m)',
    'groups.start_date': 'Boshlanish sanasi',
    'groups.end_date': 'Tugash sanasi',
    'groups.schedule_days': 'Dars kunlari',
    'groups.time_slot': 'Dars vaqti',
    'groups.enrolled_count': 'O‘quvchilar soni',
    'groups.modal_add_title': 'Yangi guruh ochish',
    'groups.modal_edit_title': 'Guruhni tahrirlash',
    'groups.modal_delete_title': 'Guruhni o‘chirish',
    'groups.delete_confirm': 'Haqiqatan ham ushbu guruhni o‘chirmoqchimisiz?',

    // Attendance
    'attendance.title': 'Davomat Daftari',
    'attendance.desc': 'Har bir dars uchun o‘quvchilarning ishtirokini tezkor belgilash va sababli qoldirishlarni kiritish.',
    'attendance.select_lesson': 'Darsni tanlang',
    'attendance.today_lessons': 'Bugungi darslar',
    'attendance.mark_all_present': 'Barchasini "Keldi" qilish',
    'attendance.save_btn': 'Davomatni saqlash',
    'attendance.saved_success': 'Davomat muvaffaqiyatli saqlandi!',
    'attendance.comment_placeholder': 'Izoh yoki sabab...',

    // Payments & Invoices
    'payments.title': 'To‘lovlar va Kassa',
    'payments.desc': 'O‘quvchilarning kurs to‘lovlari, Payme, Click va naqd pul tushumlari, invoyslar va kassa holati.',
    'payments.add_new': 'Yangi to‘lov qabul qilish',
    'payments.total_collected': 'Jami qabul qilingan',
    'payments.pending_invoices': 'Kutilayotgan invoyslar',
    'payments.search_placeholder': 'O‘quvchi yoki chek raqami bo‘yicha...',
    'payments.payment_method': 'To‘lov usuli',
    'payments.cash': 'Naqd pul',
    'payments.card': 'Karta (Terminal)',
    'payments.transfer': 'Bank o‘tkazmasi',

    // Payroll
    'payroll.title': 'Oylik Maosh va Payroll',
    'payroll.desc': 'O‘qituvchilar va xodimlarning belgilangan oylik maoshi yoki dars to‘lovlaridan foizli ulushini hisoblash.',
    'payroll.calculate_all': 'Barcha maoshlarni hisoblash',
    'payroll.total_payout': 'Jami to‘lanishi kerak',
    'payroll.paid_out': 'To‘langan summa',
    'payroll.mark_paid': 'To‘langan deb belgilash',
    'payroll.select_month': 'Oyni tanlang',

    // Reports
    'reports.title': 'Tahliliy Hisobotlar',
    'reports.desc': 'O‘quv markazining moliyaviy daromadlari, xarajatlari, talabalar harakati va o‘zlashtirish tahlillari.',
    'reports.financial': 'Moliya va Tushumlar',
    'reports.attendance': 'Davomat hisoboti',
    'reports.export_excel': 'Excel formatda yuklab olish',
    'reports.export_pdf': 'PDF hisobot',

    // Settings
    'settings.title': 'Tizim Sozlamalari',
    'settings.desc': 'O‘quv markazi ma‘lumotlari, filiallar, to‘lov tizimlari va Telegram bot integratsiyasi.',
    'settings.general': 'Umumiy sozlamalar',
    'settings.center_name': 'Markaz nomi',
    'settings.phone': 'Aloqa telefoni',
    'settings.save_btn': 'O‘zgarishlarni saqlash',

    // Grades
    'grades.title': 'Baholar Jurnali Markazi',
    'grades.desc': 'O‘quvchilarning darslardagi o‘zlashtirish ko‘rsatkichlari, ballar, test natijalari va baholash monitoringi.',
    'grades.badge': 'Baholar va Reyting 🏆',
    'grades.assessed_lessons': 'Baholangan darslar',
    'grades.tg_integration': 'Telegram integratsiya',
    'grades.students_list': 'O‘quvchilar ro‘yxati',
    'grades.save_btn': 'Baholarni Saqlash',
    'grades.saved_success': 'Baholar saqlandi! Ota-onalar Telegram orqali xabardor qilindi.',
    'grades.score': 'Ball',
    'grades.comment_placeholder': 'Izoh (masalan: Test 100%)...',
    'grades.no_students': 'Guruhda o‘quvchilar mavjud emas.',

    // Homework
    'homework.title': 'Uy Vazifalari Boshqaruvi',
    'homework.desc': 'Vazifalar berish, tekshirish, fayl biriktirish va baholash tizimi.',
    'homework.badge': 'Uy Vazifalari 📚',
    'homework.create_btn': 'Yangi vazifa yaratish',
    'homework.max_score': 'Maks. ball',
    'homework.deadline': 'Topshirish muddati',
    'homework.attached_file': 'Biriktirilgan fayl',
    'homework.submissions': 'Topshiriqlar',
    'homework.check_submissions': 'Topshiriqlarni tekshirish',
    'homework.no_homework': 'Bu guruh uchun uy vazifalari mavjud emas.',
    'homework.modal_title': 'Yangi uy vazifasi yaratish',
    'homework.task_title': 'Mavzu yoki sarlavha',
    'homework.task_desc': 'Vazifa sharti va yo‘riqnomasi',
    'homework.upload_file': 'Fayl biriktirish',
    'homework.grade_submission': 'Baholash',
    'homework.feedback': 'O‘qituvchi fikri / Izoh',
    'homework.save_grade': 'Bahoni Saqlash',

    // Lessons
    'lessons.badge': 'Akademik Dars Jadvali 📅',
    'lessons.title': 'Darslar Jadvali Markazi',
    'lessons.desc': 'Rejalashtirilgan, bugungi va o‘tilgan barcha darslar, xonalar va o‘qituvchilar monitoringi.',
    'lessons.count_unit': 'ta',

    // Payroll teacher additions
    'payroll.badge': 'Oylik Maosh va Payroll 💵',
    'payroll.my_salary_title': 'Mening Oylik Maoshim',
    'payroll.my_salary_desc': 'Har oylik hisoblangan va to‘langan maoshlar, foizlar hamda bonuslar tarixi.',

    // Profile & Parameters
    'profile.tab': 'Shaxsiy Profil & Parametrlar',
    'profile.title': 'Mening Shaxsiy Parametrlarim',
    'profile.desc': 'O‘zingizning shaxsiy ma’lumotlaringiz, telefon raqamingiz, mutaxassislik va parolingizni boshqaring.',
    'profile.first_name': 'Ism',
    'profile.last_name': 'Familiya',
    'profile.phone': 'Telefon raqami',
    'profile.email': 'Email pochta',
    'profile.specialization': 'Mutaxassislik / Fan',
    'profile.change_password': 'Parolni o‘zgartirish',
    'profile.new_password': 'Yangi parol (ixtiyoriy)',
    'profile.confirm_password': 'Yangi parolni tasdiqlash',
    'profile.save_btn': 'Profilni saqlash',
    'profile.saved_success': 'Shaxsiy ma’lumotlar muvaffaqiyatli saqlandi!',
    'profile.password_mismatch': 'Yangi parollar bir-biriga mos kelmadi!',
    'profile.role_label': 'Tizimdagi rolingiz',
    'profile.theme_label': 'Interfeys mavzusi',
    'profile.lang_label': 'Tizim tili',
  },
  RU: {
    // Nav
    'nav.dashboard': 'Панель управления',
    'nav.superadmin': 'Управление SuperAdmin',
    'nav.crm': 'CRM и Лиды',
    'nav.calendar': 'Расписание занятий',
    'nav.rooms': 'Аудитории',
    'nav.students': 'Студенты',
    'nav.teachers': 'Преподаватели',
    'nav.groups': 'Группы',
    'nav.subjects': 'Предметы',
    'nav.lessons': 'Уроки',
    'nav.attendance': 'Посещаемость',
    'nav.grades': 'Оценки',
    'nav.homework': 'Домашние задания',
    'nav.payments': 'Оплата',
    'nav.invoices': 'Счета',
    'nav.payroll': 'Зарплата и Payroll',
    'nav.risk': 'Анализ рисков',
    'nav.certificates': 'Сертификаты',
    'nav.branches': 'Филиалы',
    'nav.reports': 'Отчеты',
    'nav.settings': 'Настройки',
    'nav.my_children': 'Мои дети',
    'nav.my_profile': 'Мой профиль',
    'nav.feedback': 'Обратная связь',
    'nav.my_lessons': 'Мои уроки',
    'nav.my_groups': 'Мои группы',
    'nav.my_salary': 'Заработная плата',

    // Roles
    'role.superadmin': 'Суперадмин',
    'role.admin': 'Администратор',
    'role.teacher': 'Преподаватель',
    'role.parent': 'Родитель',
    'role.student': 'Студент',
    'role.user': 'Пользователь',

    // Header & Common
    'header.search': 'Поиск (Ctrl + K)...',
    'header.quick_add': 'Добавить',
    'header.new_student': 'Новый студент',
    'header.new_teacher': 'Новый преподаватель',
    'header.new_group': 'Новая группа',
    'header.take_attendance': 'Отметить посещаемость',
    'header.new_lead': 'Новый лид (CRM)',
    'header.logout': 'Выйти',

    // Actions
    'action.add': 'Добавить',
    'action.edit': 'Редактировать',
    'action.delete': 'Удалить',
    'action.save': 'Сохранить',
    'action.cancel': 'Отмена',
    'action.filter': 'Фильтровать',
    'action.view_all': 'Смотреть все',
    'action.loading': 'Загрузка...',
    'action.attend': 'Посещаемость',
    'action.grade': 'Оценить',
    'action.submit': 'Отправить',
    'action.details': 'Подробнее',
    'action.create_homework': '+ Новое задание',

    // Periods
    'period.analysis': 'Период анализа:',
    'period.today': 'Сегодня',
    'period.7d': '7 дней',
    'period.30d': '30 дней',
    'period.3m': '3 месяца',
    'period.6m': '6 месяцев',
    'period.1y': '1 год',
    'period.all': 'Все время',
    'period.7d_full': 'Последние 7 дней',
    'period.30d_full': 'Последние 30 дней',
    'period.3m_full': 'Последние 3 месяца',
    'period.6m_full': 'Последние 6 месяцев',
    'period.1y_full': 'Последний 1 год',
    'period.all_full': 'Все время',

    // Theme labels
    'theme.morning': 'День',
    'theme.night': 'Ночь',
    'theme.auto': 'Авто',

    // Hero Banner & Quick Actions
    'hero.morning_mode': 'Утренний активный режим',
    'hero.night_mode': 'Ночной режим защиты глаз',
    'hero.status_active': 'EduFlow Активен',
    'hero.greeting_morning': 'Добрый день',
    'hero.greeting_evening': 'Добрый вечер',
    'hero.user_fallback': 'Пользователь',
    'hero.desc_morning': 'Сегодня день новых достижений и уроков. Ваши студенты готовы к получению знаний!',
    'hero.desc_evening': 'Вы можете просмотреть отчеты о сегодняшних уроках, посещаемости и платежах. Дайте глазам отдохнуть!',
    'hero.quick_attendance': 'Быстрая посещаемость',
    'hero.students': 'Студенты',
    'hero.payments': 'Оплата',
    'hero.hub_title': 'EduFlow Pro Центр',
    'hero.hub_subtitle': 'Умная CRM система',
    'hero.quick': 'Быстрая',
    'hero.attendance': 'Посещаемость',
    'hero.telegram': 'Telegram',
    'hero.notifications': 'Уведомления',
    'hero.finance': 'Финансы',
    'hero.safe': 'Безопасное',
    'hero.cloud': 'Облако CRM',
    'hero.server_online': 'Сервер 100% Онлайн',

    'action.register_student_sub': 'Регистрация',
    'action.assign_teacher_sub': 'Назначить ментора',
    'action.create_group_sub': 'Открыть курс',
    'action.quick_mark_sub': 'Быстрая отметка',

    // Admin Dashboard
    'dash.expected_revenue': 'Ожидаемый доход',
    'dash.expected_sub': 'Оплата курсов за период',
    'dash.collected_revenue': 'Собранный доход',
    'dash.collected_sub': 'Фактически оплачено',
    'dash.debt': 'Задолженность',
    'dash.debt_sub': 'Подлежит взысканию',
    'dash.net_revenue': 'Чистый доход центра',
    'dash.net_sub': 'После вычета зарплат',
    'dash.attendance_rate': 'Посещаемость',
    'dash.attendance_sub': 'Средняя посещаемость уроков',
    'dash.average_grade': 'Средний балл',
    'dash.average_grade_sub': 'Академическая успеваемость',
    'dash.room_occupancy': 'Занятость аудиторий',
    'dash.active_rooms_suffix': 'активных аудиторий',
    'dash.risk_group': 'Группа риска',
    'dash.students_unit': 'чел.',
    'dash.total_students': 'Студенты',
    'dash.active_students': 'Активные студенты',
    'dash.teachers_count': 'Преподаватели',
    'dash.mentors_teachers': 'Менторы и преподаватели',
    'dash.active_groups': 'Активные группы',
    'dash.study_groups': 'Учебные группы',
    'dash.today_lessons': 'Уроки на сегодня',
    'dash.scheduled_lessons': 'Уроки по расписанию',
    'dash.today_lessons_schedule': 'Расписание уроков на сегодня',
    'dash.no_lessons_today': 'На сегодня уроки не запланированы',
    'dash.teacher_prefix': 'Учитель:',
    'dash.unassigned': 'Не назначен',
    'dash.students_prefix': 'Студенты:',
    'dash.no_topic': 'Тема не указана',
    'dash.time': 'Время',
    'dash.due_date_prefix': 'Срок:',
    'dash.overdue_payments': 'Задолженности',
    'dash.no_overdue': 'Просроченные платежи отсутствуют',
    'dash.monthly_revenue': 'Ежемесячный доход',
    'dash.high_risk_desc': 'Есть риск ухода студента',
    'dash.attendance_desc': 'Показатель дисциплины посещаемости занятий студентами учебного центра.',
    'dash.view_detailed_report': 'Посмотреть подробный отчет →',

    // Teacher Dashboard
    'teacher.welcome': 'Добро пожаловать',
    'teacher.badge': 'Панель преподавателя',
    'teacher.my_groups_count': 'Мои группы',
    'teacher.my_students_count': 'Мои студенты',
    'teacher.today_lessons_count': 'Уроки на сегодня',
    'teacher.monthly_earnings': 'Заработная плата (Расчет)',
    'teacher.attendance_rate': 'Средняя посещаемость',
    'teacher.today_schedule': 'Расписание моих уроков на сегодня',
    'teacher.weekly_timetable': 'Недельное расписание занятий',
    'teacher.my_groups_list': 'Мои закрепленные группы',
    'teacher.homework_title': 'Статус домашних заданий',
    'teacher.recent_grades': 'Недавно оцененные студенты',
    'teacher.quick_actions': 'Быстрые действия',
    'teacher.take_attendance_btn': 'Отметить посещаемость',
    'teacher.new_homework_btn': 'Дать домашнее задание',
    'teacher.give_grade_btn': 'Выставить оценки',
    'teacher.view_calendar_btn': 'Открыть календарь',
    'teacher.room': 'Аудитория',
    'teacher.time': 'Время',
    'teacher.group': 'Группа',
    'teacher.subject': 'Предмет',
    'teacher.topic': 'Тема',
    'teacher.students_count': 'студентов',
    'teacher.attendance_taken': 'Посещаемость отмечена',
    'teacher.attendance_pending': 'Не отмечено',
    'teacher.no_today_lessons': 'На сегодня у вас нет запланированных уроков',
    'teacher.no_homeworks': 'Активные задания отсутствуют',
    'teacher.due_date': 'Срок сдачи',
    'teacher.submissions': 'Сдали работы',
    'teacher.base_salary': 'Базовый оклад',
    'teacher.share_percent': 'Доля от оплаты',
    'teacher.payroll_status': 'Статус выплаты',
    'teacher.payroll_paid': 'Выплачено',
    'teacher.payroll_pending': 'В ожидании',
    'teacher.hero_desc': 'Ниже вы можете отслеживать расписание уроков, посещаемость студентов, оценки и расчет ежемесячной зарплаты.',
    'teacher.active_groups_sub': 'Активные учебные группы',
    'teacher.enrolled_students_sub': 'Закрепленные в группах',
    'teacher.monthly_share_sub': 'Доля за текущий месяц',
    'teacher.payroll_analysis_title': 'Анализ заработной платы и доли',
    'teacher.calculated_for_month': 'Рассчитано за этот месяц:',
    'teacher.payroll_auto_note': 'Рассчитывается автоматически на основе платежей студентов за курсы.',
    'teacher.interactive_calendar_title': 'Интерактивное расписание',
    'teacher.interactive_calendar_desc': 'Еженедельный календарь всех уроков и аудиторий',
    'teacher.open_calendar_btn': 'Открыть расписание →',
    'teacher.score_unit': 'б.',

    // Parent Dashboard
    'parent.welcome': 'Добро пожаловать, родитель',
    'parent.children': 'Мои дети',
    'parent.child_attendance': 'Посещаемость',
    'parent.child_grades': 'Последние оценки',
    'parent.child_homework': 'Домашние задания',
    'parent.child_invoices': 'Оплата и счета',
    'parent.schedule': 'Расписание занятий',
    'parent.contact_center': 'Связаться с учебным центром',

    // Statuses
    'status.active': 'Активный',
    'status.inactive': 'Неактивный',
    'status.scheduled': 'Запланирован',
    'status.completed': 'Завершен',
    'status.cancelled': 'Отменен',
    'status.present': 'Присутствовал',
    'status.absent': 'Отсутствовал',
    'status.late': 'Опоздал',
    'status.excused': 'Уважительно',
    'status.paid': 'Оплачено',
    'status.pending': 'Ожидается',
    'status.overdue': 'Задолженность',

    // Children / Portal
    'children.demo_notice_title': 'Демонстрационный профиль детей',
    'children.demo_notice_desc': 'Так как система недавно запущена, ниже отображаются примерные профили детей. Вы можете привязать реальные данные у администратора учебного центра.',
    'children.connect_child': '+ Привязать ребенка',
    'children.mgmt_badge': 'Управление детьми',
    'children.title': 'Мои дети',
    'children.subtitle': 'Управляйте расписанием занятий, преподавателями, журналом посещаемости, оценками и оплатой каждого вашего ребенка.',
    'children.link_new_btn': 'Привязать нового ребенка',
    'children.active_student': 'Активный учащийся',
    'children.debt': 'Задолженность',
    'children.paid': 'Оплачено',
    'children.attendance': 'Посещаемость',
    'children.attendance_sub': 'Присутствие',
    'children.avg_grade': 'Средний балл',
    'children.avg_grade_sub': 'Академический',
    'children.groups': 'Группы',
    'children.groups_sub': 'Прикрепленные',
    'children.assigned_courses': 'Прикрепленные курсы и группы:',
    'children.teacher': 'Преподаватель:',
    'children.monthly_tuition': 'Ежемесячная плата:',
    'children.view_full_profile': 'Посмотреть полную информацию',
    'children.no_children_title': 'Дети не найдены',
    'children.no_children_desc': 'К вашему профилю пока не привязан ни один учащийся. Вы можете привязать ребенка через администратора или по кнопке ниже.',
    'children.tab_schedule': 'Расписание уроков',
    'children.tab_attendance': 'Журнал посещаемости',
    'children.tab_grades': 'Оценки',
    'children.tab_payments': 'Оплата и счета',
    'children.present': 'Присутствовал',
    'children.absent': 'Отсутствовал',
    'children.late': 'Опоздал',
    'children.pay_with_payme': 'Оплатить через Payme',
    'children.pay_with_click': 'Оплатить через Click',
    'children.pay_with_uzum': 'Оплатить через Uzum',
    'children.close': 'Закрыть',
    'children.link_modal_title': 'Привязать ребенка к учебному центру',
    'children.link_modal_desc': 'Введите номер телефона или ID учащегося. После подтверждения администратором данные появятся в вашем профиле.',
    'children.search_placeholder': '+998 90 123 45 67 или ID учащегося...',
    'children.send_request': 'Отправить запрос на привязку',
    'children.request_sent': 'Запрос успешно отправлен! Ожидайте подтверждения от администратора.',

    // Feedback
    'feedback.page_title': 'Отзывы и предложения',
    'feedback.page_subtitle': 'Поделитесь своим мнением о центре, преподавателях и качестве уроков',
    'feedback.new_feedback': 'Оставить новый отзыв',
    'feedback.target_label': 'О чем вы хотите оставить отзыв?',
    'feedback.target_center': 'Об учебном центре',
    'feedback.target_teacher': 'О преподавателе',
    'feedback.target_course': 'О курсах и уроках',
    'feedback.target_general': 'Другое предложение',
    'feedback.select_teacher': 'Выберите преподавателя',
    'feedback.rating_label': 'Оценка (Звезды)',
    'feedback.comment_placeholder': 'Опишите ваши впечатления, пожелания или предложения подробно...',
    'feedback.submit_btn': 'Отправить отзыв',
    'feedback.success_msg': 'Ваш отзыв успешно отправлен! Спасибо.',
    'feedback.history_title': 'Все отзывы и предложения',
    'feedback.no_feedback': 'Пока нет оставленных отзывов',

    // Student Portal
    'student.badge': 'Профиль студента',
    'student.greeting': 'Привет',
    'student.hero_desc': 'Следите за расписанием, сдавайте домашние задания и отслеживайте свои результаты.',
    'student.my_groups': 'Мои группы',
    'student.active_courses': 'Активные курсы',
    'student.groups_unit': 'групп',
    'student.attendance': 'Посещаемость',
    'student.attendance_sub': 'Посещение уроков',
    'student.avg_grade': 'Средний балл',
    'student.academic_perf': 'Успеваемость',
    'student.homework_title': 'Домашние задания',
    'student.pending_count_suffix': 'ожидает сдачи',
    'student.due_date_active': 'Срок сдачи активен',
    'student.my_homework_section': 'Мои домашние задания',
    'student.tasks_unit': 'заданий',
    'student.graded_badge': 'Оценено',
    'student.submitted_badge': 'Сдано',
    'student.due_date': 'Срок',
    'student.teacher_comment': 'Комментарий учителя',
    'student.resubmit_btn': 'Пересдать / Редактировать',
    'student.submit_btn': 'Сдать задание',
    'student.no_homework': 'Домашних заданий пока нет.',
    'student.upcoming_lessons': 'Предстоящие уроки',
    'student.no_upcoming': 'В ближайшее время уроков нет.',
    'student.my_certificates': 'Мои сертификаты',
    'student.issued_date': 'Дата выдачи',
    'student.verify_btn': 'Проверить',
    'student.no_certificates': 'Сертификатов пока нет.',
    'student.submit_modal_title': 'Сдать домашнее задание',
    'student.submit_success_title': 'Успешно!',
    'student.submit_success_desc': 'Ваше задание отправлено преподавателю на проверку.',
    'student.solution_label': 'Ваш ответ или решение задания',
    'student.solution_placeholder': 'Напишите решение или текст сюда...',
    'student.attach_file_label': 'Прикрепить файл (необязательно: PDF, Word, Фото)',
    'student.choose_file': 'Выбрать файл',
    'student.file_attached': 'Файл прикреплен',
    'student.loading_portal': 'Загрузка кабинета студента...',
    'student.not_found_title': 'Данные не найдены',
    'student.not_found_desc': 'Данные студента не найдены. Пожалуйста, войдите снова.',

    // Calendar
    'calendar.title': 'Расписание уроков и Календарь',
    'calendar.subtitle': 'Занятость преподавателей, групп и аудиторий',
    'calendar.check_conflict': 'Проверить конфликт',
    'calendar.month': 'Месяц',
    'calendar.week': 'Неделя',
    'calendar.day': 'День',
    'calendar.today': 'Сегодня',
    'calendar.all_teachers': 'Все преподаватели',
    'calendar.all_groups': 'Все группы',
    'calendar.all_rooms': 'Все аудитории',
    'calendar.modal_title': 'Проверка конфликта расписания',
    'calendar.modal_desc': 'Проверьте пересечение преподавателя или аудитории перед созданием урока.',
    'calendar.start_time': 'Время начала',
    'calendar.end_time': 'Время окончания',
    'calendar.teacher_optional': 'Преподаватель (необязательно)',
    'calendar.room_optional': 'Аудитория (необязательно)',
    'calendar.group_optional': 'Группа (необязательно)',
    'calendar.select_teacher': 'Выберите преподавателя',
    'calendar.select_room': 'Выберите аудиторию',
    'calendar.select_group': 'Выберите группу',
    'calendar.checking': 'Проверка...',
    'calendar.check_btn': 'Проверить',
    'calendar.no_conflict': 'Конфликтов не обнаружено! Время свободно.',
    'calendar.conflict_found': 'Обнаружен конфликт!',
    'calendar.no_events': 'На этот период уроков нет',

    // Common Table & Pagination
    'table.name': 'Имя и фамилия',
    'table.student': 'Студент',
    'table.teacher': 'Преподаватель',
    'table.group': 'Группа',
    'table.course': 'Курс',
    'table.subject': 'Предмет',
    'table.phone': 'Телефон',
    'table.parent': 'Родитель',
    'table.status': 'Статус',
    'table.actions': 'Действия',
    'table.date': 'Дата',
    'table.time': 'Время',
    'table.room': 'Аудитория',
    'table.amount': 'Сумма',
    'table.debt': 'Задолженность',
    'table.attendance': 'Посещаемость',
    'table.grade': 'Оценка',
    'table.telegram': 'Телеграм',
    'table.page': 'Страница',
    'table.prev': 'Назад',
    'table.next': 'Вперед',

    // Students Management
    'students.title': 'Управление студентами',
    'students.desc': 'Все студенты вашего учебного центра, распределение по группам, связь с родителями и мониторинг посещаемости.',
    'students.total_enrolled': 'Всего в списке',
    'students.active_groups': 'Активные группы',
    'students.tg_integration': 'Telegram интеграция',
    'students.add_new': 'Добавить студента',
    'students.search_placeholder': 'Имя, фамилия или телефон...',
    'students.all_groups': 'Все группы',
    'students.loading': 'Загрузка списка студентов...',
    'students.empty_title': 'Добавьте первого студента или протестируйте демо-данные!',
    'students.empty_sub': 'После регистрации студента его посещаемость, платежи и связь с родителями ведутся автоматически.',
    'students.modal_add_title': 'Добавление нового студента',
    'students.modal_edit_title': 'Редактирование студента',
    'students.modal_delete_title': 'Удаление студента',
    'students.delete_confirm': 'Вы уверены, что хотите удалить этого студента?',
    'students.first_name': 'Имя',
    'students.last_name': 'Фамилия',
    'students.parent_name': 'Ф.И.О. родителя',
    'students.parent_phone': 'Телефон родителя',

    // Teachers Management
    'teachers.title': 'Преподаватели и Менторы',
    'teachers.desc': 'Преподавательский состав учебного центра, академические часы, расчет зарплат и группы.',
    'teachers.add_new': 'Добавить преподавателя',
    'teachers.search_placeholder': 'Имя или телефон преподавателя...',
    'teachers.specialization': 'Специализация',
    'teachers.salary_type': 'Тип оплаты',
    'teachers.base_salary': 'Базовая ставка',
    'teachers.share_percent': 'Процентная доля (%)',
    'teachers.fixed': 'Фиксированная зарплата',
    'teachers.percentage': 'Процент от оплат',
    'teachers.modal_add_title': 'Добавить нового преподавателя',
    'teachers.modal_edit_title': 'Редактировать преподавателя',
    'teachers.modal_delete_title': 'Удалить преподавателя',
    'teachers.delete_confirm': 'Вы уверены, что хотите удалить этого преподавателя?',

    // Groups Management
    'groups.title': 'Группы и Курсы',
    'groups.desc': 'Все учебные группы, недельные расписания, распределение аудиторий и количество учащихся.',
    'groups.add_new': 'Создать группу',
    'groups.search_placeholder': 'Поиск по названию группы...',
    'groups.all_subjects': 'Все предметы',
    'groups.all_teachers': 'Все преподаватели',
    'groups.name': 'Название группы',
    'groups.monthly_fee': 'Стоимость в месяц (сум)',
    'groups.start_date': 'Дата начала',
    'groups.end_date': 'Дата окончания',
    'groups.schedule_days': 'Дни занятий',
    'groups.time_slot': 'Время уроков',
    'groups.enrolled_count': 'Количество студентов',
    'groups.modal_add_title': 'Создание новой группы',
    'groups.modal_edit_title': 'Редактирование группы',
    'groups.modal_delete_title': 'Удаление группы',
    'groups.delete_confirm': 'Вы уверены, что хотите удалить эту группу?',

    // Attendance
    'attendance.title': 'Журнал посещаемости',
    'attendance.desc': 'Быстрая отметка посещаемости студентов на каждом уроке, фиксация причин отсутствия.',
    'attendance.select_lesson': 'Выберите урок',
    'attendance.today_lessons': 'Сегодняшние уроки',
    'attendance.mark_all_present': 'Отметить всех "Присутствовал"',
    'attendance.save_btn': 'Сохранить посещаемость',
    'attendance.saved_success': 'Посещаемость успешно сохранена!',
    'attendance.comment_placeholder': 'Комментарий или причина...',

    // Payments & Invoices
    'payments.title': 'Платежи и Касса',
    'payments.desc': 'Оплата курсов студентами, поступления через Payme, Click и наличными, счета и состояние кассы.',
    'payments.add_new': 'Принять платеж',
    'payments.total_collected': 'Всего принято',
    'payments.pending_invoices': 'Ожидающие счета',
    'payments.search_placeholder': 'По студенту или номеру чека...',
    'payments.payment_method': 'Способ оплаты',
    'payments.cash': 'Наличные',
    'payments.card': 'Карта (Терминал)',
    'payments.transfer': 'Банковский перевод',

    // Payroll
    'payroll.title': 'Заработная плата и Payroll',
    'payroll.desc': 'Автоматический расчет окладов преподавателей и сотрудников, или процента от оплаты занятий.',
    'payroll.calculate_all': 'Рассчитать все зарплаты',
    'payroll.total_payout': 'Всего к выплате',
    'payroll.paid_out': 'Выплаченная сумма',
    'payroll.mark_paid': 'Отметить как выплачено',
    'payroll.select_month': 'Выберите месяц',

    // Reports
    'reports.title': 'Аналитические отчеты',
    'reports.desc': 'Финансовые доходы и расходы учебного центра, динамика студентов и академическая успеваемость.',
    'reports.financial': 'Финансы и Выручка',
    'reports.attendance': 'Отчет по посещаемости',
    'reports.export_excel': 'Скачать в Excel',
    'reports.export_pdf': 'Скачать в PDF',

    // Settings
    'settings.title': 'Настройки системы',
    'settings.desc': 'Данные учебного центра, филиалы, платежные шлюзы и интеграция Telegram бота.',
    'settings.general': 'Основные настройки',
    'settings.center_name': 'Название центра',
    'settings.phone': 'Контактный телефон',
    'settings.save_btn': 'Сохранить изменения',

    // Grades
    'grades.title': 'Центр Журнала Оценок',
    'grades.desc': 'Успеваемость учащихся, баллы, результаты тестирований и мониторинг оценок.',
    'grades.badge': 'Оценки и Рейтинг 🏆',
    'grades.assessed_lessons': 'Оцененные уроки',
    'grades.tg_integration': 'Интеграция Telegram',
    'grades.students_list': 'Список учащихся',
    'grades.save_btn': 'Сохранить Оценки',
    'grades.saved_success': 'Оценки успешно сохранены! Родители уведомлены в Telegram.',
    'grades.score': 'Балл',
    'grades.comment_placeholder': 'Комментарий (напр: Тест 100%)...',
    'grades.no_students': 'В группе пока нет учащихся.',

    // Homework
    'homework.title': 'Управление Домашними Заданиями',
    'homework.desc': 'Выдача, проверка, прикрепление файлов и оценивание заданий.',
    'homework.badge': 'Домашние Задания 📚',
    'homework.create_btn': 'Создать задание',
    'homework.max_score': 'Макс. балл',
    'homework.deadline': 'Срок сдачи',
    'homework.attached_file': 'Прикрепленный файл',
    'homework.submissions': 'Ответы учащихся',
    'homework.check_submissions': 'Проверить ответы',
    'homework.no_homework': 'Для этой группы нет домашних заданий.',
    'homework.modal_title': 'Создать новое задание',
    'homework.task_title': 'Тема или заголовок',
    'homework.task_desc': 'Условие задания и инструкции',
    'homework.upload_file': 'Прикрепить файл',
    'homework.grade_submission': 'Оценить',
    'homework.feedback': 'Отзыв преподавателя / Комментарий',
    'homework.save_grade': 'Сохранить Оценку',

    // Lessons
    'lessons.badge': 'Академическое Расписание 📅',
    'lessons.title': 'Центр Расписания Уроков',
    'lessons.desc': 'Мониторинг запланированных, сегодняшних и проведенных уроков, кабинетов и преподавателей.',
    'lessons.count_unit': 'ур.',

    // Payroll teacher additions
    'payroll.badge': 'Заработная Плата и Payroll 💵',
    'payroll.my_salary_title': 'Моя Заработная Плата',
    'payroll.my_salary_desc': 'История начисленной и выплаченной зарплаты, процентов и бонусов по месяцам.',

    // Profile & Parameters
    'profile.tab': 'Личный Профиль и Параметры',
    'profile.title': 'Мои Личные Параметры',
    'profile.desc': 'Управляйте личными данными, номером телефона, специализацией и паролем учетной записи.',
    'profile.first_name': 'Имя',
    'profile.last_name': 'Фамилия',
    'profile.phone': 'Номер телефона',
    'profile.email': 'Электронная почта',
    'profile.specialization': 'Специализация / Предмет',
    'profile.change_password': 'Сменить пароль',
    'profile.new_password': 'Новый пароль (необязательно)',
    'profile.confirm_password': 'Подтвердите новый пароль',
    'profile.save_btn': 'Сохранить профиль',
    'profile.saved_success': 'Личные данные успешно обновлены!',
    'profile.password_mismatch': 'Пароли не совпадают!',
    'profile.role_label': 'Ваша роль в системе',
    'profile.theme_label': 'Тема оформления',
    'profile.lang_label': 'Язык интерфейса',
  },
  EN: {
    // Nav
    'nav.dashboard': 'Dashboard',
    'nav.superadmin': 'SuperAdmin Panel',
    'nav.crm': 'CRM & Leads',
    'nav.calendar': 'Class Schedule',
    'nav.rooms': 'Rooms',
    'nav.students': 'Students',
    'nav.teachers': 'Teachers',
    'nav.groups': 'Groups',
    'nav.subjects': 'Subjects',
    'nav.lessons': 'Lessons',
    'nav.attendance': 'Attendance',
    'nav.grades': 'Grades',
    'nav.homework': 'Homework',
    'nav.payments': 'Payments',
    'nav.invoices': 'Invoices',
    'nav.payroll': 'Payroll & Salary',
    'nav.risk': 'Risk Analysis',
    'nav.certificates': 'Certificates',
    'nav.branches': 'Branches',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    'nav.my_children': 'My Children',
    'nav.my_profile': 'My Profile',
    'nav.feedback': 'Feedback',
    'nav.my_lessons': 'My Lessons',
    'nav.my_groups': 'My Groups',
    'nav.my_salary': 'My Salary',

    // Roles
    'role.superadmin': 'SuperAdmin',
    'role.admin': 'Administrator',
    'role.teacher': 'Teacher',
    'role.parent': 'Parent',
    'role.student': 'Student',
    'role.user': 'User',

    // Header & Common
    'header.search': 'Search (Ctrl + K)...',
    'header.quick_add': 'Quick Add',
    'header.new_student': 'New Student',
    'header.new_teacher': 'New Teacher',
    'header.new_group': 'New Group',
    'header.take_attendance': 'Take Attendance',
    'header.new_lead': 'New Lead (CRM)',
    'header.logout': 'Sign Out',

    // Actions
    'action.add': 'Add',
    'action.edit': 'Edit',
    'action.delete': 'Delete',
    'action.save': 'Save',
    'action.cancel': 'Cancel',
    'action.filter': 'Filter',
    'action.view_all': 'View All',
    'action.loading': 'Loading...',
    'action.attend': 'Attendance',
    'action.grade': 'Grade',
    'action.submit': 'Submit',
    'action.details': 'Details',
    'action.create_homework': '+ New Homework',

    // Periods
    'period.analysis': 'Analysis Period:',
    'period.today': 'Today',
    'period.7d': '7 Days',
    'period.30d': '30 Days',
    'period.3m': '3 Months',
    'period.6m': '6 Months',
    'period.1y': '1 Year',
    'period.all': 'All Time',
    'period.7d_full': 'Last 7 Days',
    'period.30d_full': 'Last 30 Days',
    'period.3m_full': 'Last 3 Months',
    'period.6m_full': 'Last 6 Months',
    'period.1y_full': 'Last 1 Year',
    'period.all_full': 'All Time',

    // Theme labels
    'theme.morning': 'Morning',
    'theme.night': 'Night',
    'theme.auto': 'Auto',

    // Hero Banner & Quick Actions
    'hero.morning_mode': 'Morning Focus Mode',
    'hero.night_mode': 'Night Eye-Care Mode',
    'hero.status_active': 'EduFlow Active',
    'hero.greeting_morning': 'Good day',
    'hero.greeting_evening': 'Good evening',
    'hero.user_fallback': 'User',
    'hero.desc_morning': 'Today is a day of new achievements and lessons. Your students are ready to learn!',
    'hero.desc_evening': 'You can review today’s lessons, attendance, and payment reports. Take a rest!',
    'hero.quick_attendance': 'Quick Attendance',
    'hero.students': 'Students',
    'hero.payments': 'Payments',
    'hero.hub_title': 'EduFlow Pro Hub',
    'hero.hub_subtitle': 'Multi-Tenant Smart CRM',
    'hero.quick': 'Quick',
    'hero.attendance': 'Attendance',
    'hero.telegram': 'Telegram',
    'hero.notifications': 'Alerts',
    'hero.finance': 'Finance',
    'hero.safe': 'Secure',
    'hero.cloud': 'Cloud System',
    'hero.server_online': 'Server 100% Online',

    'action.register_student_sub': 'Registration',
    'action.assign_teacher_sub': 'Assign mentor',
    'action.create_group_sub': 'Open course',
    'action.quick_mark_sub': 'Quick mark',

    // Admin Dashboard
    'dash.expected_revenue': 'Expected Revenue',
    'dash.expected_sub': 'Course fees for period',
    'dash.collected_revenue': 'Collected Revenue',
    'dash.collected_sub': 'Actually collected',
    'dash.debt': 'Outstanding Debt',
    'dash.debt_sub': 'To be collected',
    'dash.net_revenue': 'Center Net Profit',
    'dash.net_sub': 'After salary deductions',
    'dash.attendance_rate': 'Attendance Rate',
    'dash.attendance_sub': 'Average class attendance',
    'dash.average_grade': 'Average Grade',
    'dash.average_grade_sub': 'Academic performance',
    'dash.room_occupancy': 'Room Occupancy',
    'dash.active_rooms_suffix': 'active rooms',
    'dash.risk_group': 'Risk Group',
    'dash.students_unit': 'students',
    'dash.total_students': 'Students',
    'dash.active_students': 'Active students',
    'dash.teachers_count': 'Teachers',
    'dash.mentors_teachers': 'Mentors & Teachers',
    'dash.active_groups': 'Active Groups',
    'dash.study_groups': 'Study groups',
    'dash.today_lessons': 'Today\'s Lessons',
    'dash.scheduled_lessons': 'Scheduled lessons',
    'dash.today_lessons_schedule': 'Today\'s Lesson Timetable',
    'dash.no_lessons_today': 'No lessons scheduled for today',
    'dash.teacher_prefix': 'Teacher:',
    'dash.unassigned': 'Unassigned',
    'dash.students_prefix': 'Students:',
    'dash.no_topic': 'No topic specified',
    'dash.time': 'Time',
    'dash.due_date_prefix': 'Due:',
    'dash.overdue_payments': 'Overdue Debts',
    'dash.no_overdue': 'No overdue payments currently',
    'dash.monthly_revenue': 'Monthly Revenue',
    'dash.high_risk_desc': 'At risk of dropping out',
    'dash.attendance_desc': 'Overall student attendance discipline metric across the learning center.',
    'dash.view_detailed_report': 'View detailed report →',

    // Teacher Dashboard
    'teacher.welcome': 'Welcome',
    'teacher.badge': 'Teacher Dashboard',
    'teacher.my_groups_count': 'My Groups',
    'teacher.my_students_count': 'My Students',
    'teacher.today_lessons_count': 'Today\'s Lessons',
    'teacher.monthly_earnings': 'Monthly Salary (Estimated)',
    'teacher.attendance_rate': 'Average Attendance',
    'teacher.today_schedule': 'My Today\'s Schedule',
    'teacher.weekly_timetable': 'Weekly Class Timetable',
    'teacher.my_groups_list': 'My Assigned Groups',
    'teacher.homework_title': 'Homework Status',
    'teacher.recent_grades': 'Recently Graded Students',
    'teacher.quick_actions': 'Quick Actions',
    'teacher.take_attendance_btn': 'Take Attendance',
    'teacher.new_homework_btn': 'Assign Homework',
    'teacher.give_grade_btn': 'Enter Grades',
    'teacher.view_calendar_btn': 'View Calendar',
    'teacher.room': 'Room',
    'teacher.time': 'Time',
    'teacher.group': 'Group',
    'teacher.subject': 'Subject',
    'teacher.topic': 'Topic',
    'teacher.students_count': 'students',
    'teacher.attendance_taken': 'Attendance taken',
    'teacher.attendance_pending': 'Pending attendance',
    'teacher.no_today_lessons': 'No lessons scheduled for you today',
    'teacher.no_homeworks': 'No active homework assignments',
    'teacher.due_date': 'Due Date',
    'teacher.submissions': 'Submissions',
    'teacher.base_salary': 'Base Salary',
    'teacher.share_percent': 'Share Percentage',
    'teacher.payroll_status': 'Payroll Status',
    'teacher.payroll_paid': 'Paid',
    'teacher.payroll_pending': 'Pending',
    'teacher.hero_desc': 'Below you can track your lesson schedule, student attendance, grades, and monthly earnings breakdown.',
    'teacher.active_groups_sub': 'Active study groups',
    'teacher.enrolled_students_sub': 'Enrolled in groups',
    'teacher.monthly_share_sub': 'Current month\'s share',
    'teacher.payroll_analysis_title': 'Monthly Salary & Share Analysis',
    'teacher.calculated_for_month': 'Calculated for this month:',
    'teacher.payroll_auto_note': 'Calculated automatically based on course fees paid by students.',
    'teacher.interactive_calendar_title': 'Interactive Timetable',
    'teacher.interactive_calendar_desc': 'Weekly calendar of all classes and classrooms',
    'teacher.open_calendar_btn': 'Open timetable →',
    'teacher.score_unit': 'pts',

    // Parent Dashboard
    'parent.welcome': 'Welcome, Parent',
    'parent.children': 'My Children',
    'parent.child_attendance': 'Attendance Rate',
    'parent.child_grades': 'Recent Grades',
    'parent.child_homework': 'Homework',
    'parent.child_invoices': 'Invoices & Payments',
    'parent.schedule': 'Class Schedule',
    'parent.contact_center': 'Contact Center',

    // Statuses
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.scheduled': 'Scheduled',
    'status.completed': 'Completed',
    'status.cancelled': 'Cancelled',
    'status.present': 'Present',
    'status.absent': 'Absent',
    'status.late': 'Late',
    'status.excused': 'Excused',
    'status.paid': 'Paid',
    'status.pending': 'Pending',
    'status.overdue': 'Overdue',

    // Children / Portal
    'children.demo_notice_title': 'Demonstration Children Profile',
    'children.demo_notice_desc': 'As the system was recently started, sample children profiles are shown below. You can link your actual children through center administrators.',
    'children.connect_child': '+ Link Child',
    'children.mgmt_badge': 'My Children Management',
    'children.title': 'My Children',
    'children.subtitle': 'Manage class schedules, teachers, attendance logs, grades, and tuition payments individually for each child.',
    'children.link_new_btn': 'Link New Child',
    'children.active_student': 'Active Student',
    'children.debt': 'Overdue Debt',
    'children.paid': 'Paid Up',
    'children.attendance': 'Attendance',
    'children.attendance_sub': 'Presence',
    'children.avg_grade': 'Average Grade',
    'children.avg_grade_sub': 'Academic',
    'children.groups': 'Groups',
    'children.groups_sub': 'Enrolled',
    'children.assigned_courses': 'Enrolled courses and groups:',
    'children.teacher': 'Teacher:',
    'children.monthly_tuition': 'Monthly Tuition:',
    'children.view_full_profile': 'View Full Profile',
    'children.no_children_title': 'No Children Found',
    'children.no_children_desc': 'No students are linked to your parent account yet. Link your child with the administrator or by clicking below.',
    'children.tab_schedule': 'Class Schedule',
    'children.tab_attendance': 'Attendance Log',
    'children.tab_grades': 'Grades',
    'children.tab_payments': 'Payment & Invoices',
    'children.present': 'Present',
    'children.absent': 'Absent',
    'children.late': 'Late',
    'children.pay_with_payme': 'Pay via Payme',
    'children.pay_with_click': 'Pay via Click',
    'children.pay_with_uzum': 'Pay via Uzum',
    'children.close': 'Close',
    'children.link_modal_title': 'Link Child to Learning Center',
    'children.link_modal_desc': 'Enter your child\'s phone number or Student ID. Once approved by center administrators, their full profile will appear.',
    'children.search_placeholder': '+998 90 123 45 67 or Student ID...',
    'children.send_request': 'Submit Link Request',
    'children.request_sent': 'Request sent successfully! Awaiting administrator approval.',

    // Feedback
    'feedback.page_title': 'Feedback & Suggestions',
    'feedback.page_subtitle': 'Share your feedback regarding the center, teachers, and lesson quality',
    'feedback.new_feedback': 'Leave Feedback',
    'feedback.target_label': 'What is your feedback about?',
    'feedback.target_center': 'About Learning Center',
    'feedback.target_teacher': 'About Teacher',
    'feedback.target_course': 'About Courses & Lessons',
    'feedback.target_general': 'General Suggestion',
    'feedback.select_teacher': 'Select Teacher',
    'feedback.rating_label': 'Rating (Stars)',
    'feedback.comment_placeholder': 'Write your feedback, suggestions, or comments in detail...',
    'feedback.submit_btn': 'Submit Feedback',
    'feedback.success_msg': 'Your feedback was successfully submitted! Thank you.',
    'feedback.history_title': 'All Feedback & Suggestions',
    'feedback.no_feedback': 'No feedback submitted yet',

    // Student Portal
    'student.badge': 'Student Profile',
    'student.greeting': 'Hello',
    'student.hero_desc': 'Track your class schedule, submit homework, and monitor your academic progress.',
    'student.my_groups': 'My Groups',
    'student.active_courses': 'Active courses',
    'student.groups_unit': 'groups',
    'student.attendance': 'Attendance',
    'student.attendance_sub': 'Class attendance',
    'student.avg_grade': 'Average Grade',
    'student.academic_perf': 'Academic performance',
    'student.homework_title': 'Homework',
    'student.pending_count_suffix': 'pending',
    'student.due_date_active': 'Due date active',
    'student.my_homework_section': 'My Homework Assignments',
    'student.tasks_unit': 'tasks',
    'student.graded_badge': 'Graded',
    'student.submitted_badge': 'Submitted',
    'student.due_date': 'Due Date',
    'student.teacher_comment': 'Teacher\'s comment',
    'student.resubmit_btn': 'Resubmit / Edit',
    'student.submit_btn': 'Submit Homework',
    'student.no_homework': 'No homework assignments yet.',
    'student.upcoming_lessons': 'Upcoming Lessons',
    'student.no_upcoming': 'No upcoming lessons scheduled.',
    'student.my_certificates': 'My Certificates',
    'student.issued_date': 'Issued Date',
    'student.verify_btn': 'Verify',
    'student.no_certificates': 'No certificates issued yet.',
    'student.submit_modal_title': 'Submit Homework',
    'student.submit_success_title': 'Success!',
    'student.submit_success_desc': 'Your homework has been submitted to the teacher for review.',
    'student.solution_label': 'Your solution or comments',
    'student.solution_placeholder': 'Write your solution or essay text here...',
    'student.attach_file_label': 'Attach file (optional: PDF, Word, Image)',
    'student.choose_file': 'Choose file',
    'student.file_attached': 'File attached',
    'student.loading_portal': 'Loading student portal...',
    'student.not_found_title': 'Information Not Found',
    'student.not_found_desc': 'Student information not found in the system. Please log in again.',

    // Calendar
    'calendar.title': 'Class Schedule & Calendar',
    'calendar.subtitle': 'Teachers, groups and classroom occupancy',
    'calendar.check_conflict': 'Check Conflict',
    'calendar.month': 'Month',
    'calendar.week': 'Week',
    'calendar.day': 'Day',
    'calendar.today': 'Today',
    'calendar.all_teachers': 'All Teachers',
    'calendar.all_groups': 'All Groups',
    'calendar.all_rooms': 'All Rooms',
    'calendar.modal_title': 'Timetable Conflict Check',
    'calendar.modal_desc': 'Detect room or teacher collisions before scheduling lessons.',
    'calendar.start_time': 'Start Time',
    'calendar.end_time': 'End Time',
    'calendar.teacher_optional': 'Teacher (optional)',
    'calendar.room_optional': 'Room (optional)',
    'calendar.group_optional': 'Group (optional)',
    'calendar.select_teacher': 'Select Teacher',
    'calendar.select_room': 'Select Room',
    'calendar.select_group': 'Select Group',
    'calendar.checking': 'Checking...',
    'calendar.check_btn': 'Run Check',
    'calendar.no_conflict': 'No conflicts detected! The slot is free.',
    'calendar.conflict_found': 'Conflict Detected!',
    'calendar.no_events': 'No lessons scheduled for this period',

    // Common Table & Pagination
    'table.name': 'Full Name',
    'table.student': 'Student',
    'table.teacher': 'Teacher',
    'table.group': 'Group',
    'table.course': 'Course',
    'table.subject': 'Subject',
    'table.phone': 'Phone',
    'table.parent': 'Parent',
    'table.status': 'Status',
    'table.actions': 'Actions',
    'table.date': 'Date',
    'table.time': 'Time',
    'table.room': 'Room',
    'table.amount': 'Amount',
    'table.debt': 'Outstanding Debt',
    'table.attendance': 'Attendance',
    'table.grade': 'Grade',
    'table.telegram': 'Telegram',
    'table.page': 'Page',
    'table.prev': 'Previous',
    'table.next': 'Next',

    // Students Management
    'students.title': 'Student Management',
    'students.desc': 'All students of your learning center, group distribution, Telegram parent notifications, and monthly attendance tracking.',
    'students.total_enrolled': 'Total Enrolled',
    'students.active_groups': 'Active Groups',
    'students.tg_integration': 'Telegram Integration',
    'students.add_new': 'Add New Student',
    'students.search_placeholder': 'Name, surname or phone...',
    'students.all_groups': 'All Groups',
    'students.loading': 'Loading students list...',
    'students.empty_title': 'Add your first student or explore demo data!',
    'students.empty_sub': 'Once enrolled, student attendance, tuition fees, and parent communication are handled automatically.',
    'students.modal_add_title': 'Add New Student',
    'students.modal_edit_title': 'Edit Student Details',
    'students.modal_delete_title': 'Delete Student',
    'students.delete_confirm': 'Are you sure you want to remove this student?',
    'students.first_name': 'First Name',
    'students.last_name': 'Last Name',
    'students.parent_name': 'Parent\'s Full Name',
    'students.parent_phone': 'Parent\'s Phone',

    // Teachers Management
    'teachers.title': 'Teachers & Mentors',
    'teachers.desc': 'Learning center faculty, lesson hours, salary calculations, and group assignments.',
    'teachers.add_new': 'Add New Teacher',
    'teachers.search_placeholder': 'Teacher name or phone...',
    'teachers.specialization': 'Specialization',
    'teachers.salary_type': 'Salary Type',
    'teachers.base_salary': 'Base Rate',
    'teachers.share_percent': 'Share Percentage (%)',
    'teachers.fixed': 'Fixed Salary',
    'teachers.percentage': 'Percentage Share',
    'teachers.modal_add_title': 'Add New Teacher',
    'teachers.modal_edit_title': 'Edit Teacher Details',
    'teachers.modal_delete_title': 'Delete Teacher',
    'teachers.delete_confirm': 'Are you sure you want to delete this teacher?',

    // Groups Management
    'groups.title': 'Groups & Courses',
    'groups.desc': 'All study groups, weekly schedules, classroom allocations, and enrolled student counts.',
    'groups.add_new': 'Create New Group',
    'groups.search_placeholder': 'Search by group name...',
    'groups.all_subjects': 'All Subjects',
    'groups.all_teachers': 'All Teachers',
    'groups.name': 'Group Name',
    'groups.monthly_fee': 'Monthly Fee (UZS)',
    'groups.start_date': 'Start Date',
    'groups.end_date': 'End Date',
    'groups.schedule_days': 'Lesson Days',
    'groups.time_slot': 'Time Slot',
    'groups.enrolled_count': 'Enrolled Students',
    'groups.modal_add_title': 'Create New Group',
    'groups.modal_edit_title': 'Edit Group',
    'groups.modal_delete_title': 'Delete Group',
    'groups.delete_confirm': 'Are you sure you want to delete this group?',

    // Attendance
    'attendance.title': 'Attendance Register',
    'attendance.desc': 'Quickly mark student presence for each lesson, log excused absences, and notify parents.',
    'attendance.select_lesson': 'Select Lesson',
    'attendance.today_lessons': 'Today\'s Lessons',
    'attendance.mark_all_present': 'Mark All "Present"',
    'attendance.save_btn': 'Save Attendance',
    'attendance.saved_success': 'Attendance successfully saved!',
    'attendance.comment_placeholder': 'Note or reason...',

    // Payments & Invoices
    'payments.title': 'Payments & Cashflow',
    'payments.desc': 'Student tuition payments, Payme, Click and cash receipts, invoices, and cash balance.',
    'payments.add_new': 'Receive Payment',
    'payments.total_collected': 'Total Collected',
    'payments.pending_invoices': 'Pending Invoices',
    'payments.search_placeholder': 'By student or receipt number...',
    'payments.payment_method': 'Payment Method',
    'payments.cash': 'Cash',
    'payments.card': 'Card (POS Terminal)',
    'payments.transfer': 'Bank Transfer',

    // Payroll
    'payroll.title': 'Payroll & Salaries',
    'payroll.desc': 'Automatic calculation of fixed salaries or tuition share percentages for teachers and staff.',
    'payroll.calculate_all': 'Calculate All Salaries',
    'payroll.total_payout': 'Total Payout',
    'payroll.paid_out': 'Paid Out',
    'payroll.mark_paid': 'Mark as Paid',
    'payroll.select_month': 'Select Month',

    // Reports
    'reports.title': 'Analytics & Reports',
    'reports.desc': 'Learning center financial performance, expenses, student retention, and academic metrics.',
    'reports.financial': 'Finance & Revenue',
    'reports.attendance': 'Attendance Report',
    'reports.export_excel': 'Download Excel',
    'reports.export_pdf': 'Download PDF',

    // Settings
    'settings.title': 'System Settings',
    'settings.desc': 'Center profile, branches, payment gateways, and Telegram bot integration.',
    'settings.general': 'General Settings',
    'settings.center_name': 'Center Name',
    'settings.phone': 'Contact Phone',
    'settings.save_btn': 'Save Changes',

    // Grades
    'grades.title': 'Gradebook & Assessment Center',
    'grades.desc': 'Student academic performance, test scores, grades, and automated parent alerts.',
    'grades.badge': 'Grades & Ranking 🏆',
    'grades.assessed_lessons': 'Assessed Lessons',
    'grades.tg_integration': 'Telegram Integration',
    'grades.students_list': 'Students List',
    'grades.save_btn': 'Save Grades',
    'grades.saved_success': 'Grades saved successfully! Parents notified via Telegram.',
    'grades.score': 'Score',
    'grades.comment_placeholder': 'Comment (e.g. Quiz 100%)...',
    'grades.no_students': 'No students in this group yet.',

    // Homework
    'homework.title': 'Homework Management',
    'homework.desc': 'Assigning tasks, reviewing submissions, attaching files, and grading.',
    'homework.badge': 'Homework Hub 📚',
    'homework.create_btn': 'Create New Homework',
    'homework.max_score': 'Max Score',
    'homework.deadline': 'Submission Deadline',
    'homework.attached_file': 'Attached File',
    'homework.submissions': 'Submissions',
    'homework.check_submissions': 'Review Submissions',
    'homework.no_homework': 'No homework assigned to this group yet.',
    'homework.modal_title': 'Create New Assignment',
    'homework.task_title': 'Topic or Title',
    'homework.task_desc': 'Task instructions and description',
    'homework.upload_file': 'Attach File',
    'homework.grade_submission': 'Grade Submission',
    'homework.feedback': 'Teacher Feedback / Comments',
    'homework.save_grade': 'Save Grade',

    // Lessons
    'lessons.badge': 'Academic Lesson Schedule 📅',
    'lessons.title': 'Lesson Schedule Center',
    'lessons.desc': 'Monitoring of scheduled, today’s, and completed lessons, rooms, and teachers.',
    'lessons.count_unit': 'lessons',

    // Payroll teacher additions
    'payroll.badge': 'Salaries & Payroll 💵',
    'payroll.my_salary_title': 'My Salary History',
    'payroll.my_salary_desc': 'Monthly record of calculated, accrued, and disbursed salaries, percentages, and bonuses.',

    // Profile & Parameters
    'profile.tab': 'Personal Profile & Settings',
    'profile.title': 'My Personal Settings',
    'profile.desc': 'Manage your personal profile, phone number, specialization, and account security.',
    'profile.first_name': 'First Name',
    'profile.last_name': 'Last Name',
    'profile.phone': 'Phone Number',
    'profile.email': 'Email Address',
    'profile.specialization': 'Specialization / Subject',
    'profile.change_password': 'Change Password',
    'profile.new_password': 'New Password (optional)',
    'profile.confirm_password': 'Confirm New Password',
    'profile.save_btn': 'Save Profile',
    'profile.saved_success': 'Personal profile successfully updated!',
    'profile.password_mismatch': 'Passwords do not match!',
    'profile.role_label': 'Your system role',
    'profile.theme_label': 'Interface Theme',
    'profile.lang_label': 'System Language',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const location = useLocation();
  const navigate = useNavigate();

  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const match = window.location.pathname.match(/^\/(uz|ru|en)(\/|$)/i);
      if (match) {
        return match[1].toUpperCase() as Language;
      }
    }
    const saved = localStorage.getItem('eduflow_lang') as Language;
    if (saved && (saved === 'UZ' || saved === 'RU' || saved === 'EN')) {
      return saved;
    }
    return 'UZ';
  });

  // Sync state if URL prefix changes
  useEffect(() => {
    const match = location.pathname.match(/^\/(uz|ru|en)(\/|$)/i);
    if (match) {
      const urlLang = match[1].toUpperCase() as Language;
      if (urlLang !== language) {
        setLanguageState(urlLang);
        localStorage.setItem('eduflow_lang', urlLang);
      }
    }
  }, [location.pathname, language]);

  const setLanguage = (newLang: Language) => {
    setLanguageState(newLang);
    localStorage.setItem('eduflow_lang', newLang);

    const currentPath = location.pathname;
    const currentSearch = location.search;
    const currentHash = location.hash;

    const match = currentPath.match(/^\/(uz|ru|en)(\/.*|$)/i);
    let nextPath: string;
    if (match) {
      const rest = match[2] || '';
      nextPath = `/${newLang.toLowerCase()}${rest.startsWith('/') ? rest : rest ? '/' + rest : ''}`;
    } else {
      nextPath = `/${newLang.toLowerCase()}${currentPath.startsWith('/') ? currentPath : '/' + currentPath}`;
    }

    if (nextPath !== currentPath) {
      navigate(`${nextPath}${currentSearch}${currentHash}`, { replace: true });
    }
  };

  const t = (key: string, fallback?: string): string => {
    const currentDict = translations[language];
    if (currentDict && currentDict[key]) {
      return currentDict[key];
    }
    // Fallback to UZ
    if (translations.UZ[key]) {
      return translations.UZ[key];
    }
    return fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
